jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - group: certbot-common
    strategy:
      matrix:
        farmtest-apache2:
          PYTHON_VERSION: 3.7
          TOXENV: test-farm-apache2
        farmtest-leauto-upgrades:
          PYTHON_VERSION: 3.7
          TOXENV: test-farm-leauto-upgrades
        farmtest-certonly-standalone:
          PYTHON_VERSION: 3.7
          TOXENV: test-farm-certonly-standalone
        farmtest-sdists:
          PYTHON_VERSION: 3.7
          TOXENV: test-farm-sdists
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
