jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - name: PYTHON_VERSION
        value: 3.8
      - group: certbot-common
    strategy:
      matrix:
        linux-boulder-v1-integration-certbot-oldest:
          TOXENV: integration-certbot-oldest
          ACME_SERVER: boulder-v1
        linux-boulder-v2-integration-certbot-oldest:
          TOXENV: integration-certbot-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v1-integration-nginx-oldest:
          TOXENV: integration-nginx-oldest
          ACME_SERVER: boulder-v1
        linux-boulder-v2-integration-nginx-oldest:
          TOXENV: integration-nginx-oldest
          ACME_SERVER: boulder-v2
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
