jobs:
  - job: snap_build
    strategy:
      matrix:
        arm64:
          ARCH: arm64
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          tools/snap/build.sh ${ARCH}
          mv *.snap $(Build.ArtifactStagingDirectory)
        displayName: Build Certbot snap
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: snap-$(arch)
        displayName: Store snap artifact
  - job: snap_dns_build
    strategy:
      matrix:
        arm64:
          ARCH: arm64
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          tools/snap/build_dns.sh ${ARCH} ALL
          mv certbot-dns-*/*.snap $(Build.ArtifactStagingDirectory)
        displayName: Build Certbot DNS snaps
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: dns-snap-$(arch)
        displayName: Store snaps artifacts
