jobs:
  - job: snap_build
    strategy:
      matrix:
        amd64:
          ARCH: amd64
        # Do not run the QEMU jobs for test branches
        ${{ if not(startsWith(variables['Build.SourceBranchName'], 'test-')) }}:
          arm64:
            ARCH: arm64
          armhf:
            ARCH: armhf
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          tools/snap/build.sh ${ARCH}
          mv *.snap $(Build.ArtifactStagingDirectory)
        displayName: Build Certbot snap
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: snap-$(arch)
        displayName: Store snap artifact
  - job: snap_dns_build
    strategy:
      matrix:
        amd64:
          ARCH: amd64
        # Do not run the QEMU jobs for test branches
        ${{ if not(startsWith(variables['Build.SourceBranchName'], 'test-')) }}:
          arm64:
            ARCH: arm64
          armhf:
            ARCH: armhf
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          tools/snap/build_dns.sh ${ARCH} ALL
          mv certbot-dns-*/*.snap $(Build.ArtifactStagingDirectory)
        displayName: Build Certbot DNS snaps
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: dns-snap-$(arch)
        displayName: Store snaps artifacts
  - job: snap_run
    dependsOn: snap_build
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends nginx-light snapd
          python tools/pip_install.py -U tox
        displayName: Install dependencies
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: snap-amd64
          path: $(Build.SourcesDirectory)/snap
        displayName: Retrieve Certbot snap
      - script: |
          sudo snap install --dangerous --classic snap/*.snap
        displayName: Install Certbot snap
      - script: |
          python -m tox -e integration-external,apacheconftest-external-with-pebble
        displayName: Run tox
  - job: snap_dns_run
    dependsOn:
      - snap_build
      - snap_dns_build
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends snapd
        displayName: Install dependencies
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
          addToPath: true
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: snap-amd64
          path: $(Build.SourcesDirectory)/snap
        displayName: Retrieve Certbot snap
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: dns-snap-amd64
          path: $(Build.SourcesDirectory)/snap
        displayName: Retrieve Certbot DNS plugins snaps
      - script: |
          python3 -m venv venv
          venv/bin/python tools/pip_install.py -e certbot-ci
        displayName: Prepare Certbot-CI
      - script: |
          sudo -E venv/bin/pytest certbot-ci/snap_integration_tests/dns_tests --allow-persistent-changes --snap-folder $(Build.SourcesDirectory)/snap
        displayName: Test DNS plugins snaps
