jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.8
    strategy:
      matrix:
        linux-oldest-tests-1:
          IMAGE_NAME: ubuntu-18.04
          TOXENV: py27-{acme,apache,apache-v2,certbot}-oldest
        linux-oldest-tests-2:
          IMAGE_NAME: ubuntu-18.04
          TOXENV: py27-{dns,nginx}-oldest
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
