jobs:
  - job: test
    strategy:
      matrix:
        linux-py27:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 2.7
          TOXENV: py27
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
