jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.8
    strategy:
      matrix:
        apacheconftest:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 2.7
          TOXENV: apacheconftest-with-pebble
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
