steps:
  - bash: |
      brew install augeas
    condition: startswith(pool.vmImage, 'macOS')
    displayName: Install MacOS dependencies
  - bash: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends \
        python-dev \
        gcc \
        libaugeas0 \
        libssl-dev \
        libffi-dev \
        ca-certificates \
        nginx-light \
        openssl \
        expect
    condition: startswith(pool.vmImage, 'ubuntu')
    displayName: Install Linux dependencies
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      addToPath: true
    condition: ne(coalesce(variables['PYTHON_VERSION'], 'UNSPECIFIED'), 'UNSPECIFIED')
    displayName: Activate selected Python version
  - bash: |
      python tools/pip_install.py -U tox coverage
    displayName: Install runtime dependencies
  - bash: |
      if command -v unbuffer > /dev/null 2> &1; then
        unbuffer -p python -m tox
      else
        python -m tox
      fi
    displayName: Run tox
