name: certbot-dns-dnsimple
summary: DNSimple DNS Authenticator plugin for Certbot
description: DNSimple DNS Authenticator plugin for Certbot
confinement: strict
grade: devel
base: core20
adopt-info: certbot-dns-dnsimple

parts:
  certbot-dns-dnsimple:
    plugin: python
    source: .
    constraints: [$SNAPCRAFT_PART_SRC/snap-constraints.txt]
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version $SNAPCRAFT_PART_SRC/setup.py | cut -f2 -d= | tr -d "'[:space:]"`
    build-environment:
      - EXCLUDE_CERTBOT_DEPS: "True"
  certbot-version:
    plugin: dump
    source: .
    stage: [setup.py]

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-version:
    interface: content
    content: version-1
    target: $SNAP/certbot-version

hooks:
  post-refresh:
    plugs: [certbot-version]