parameters:
- name: snapReleaseChannel
  type: string
  default: edge
  values:
  - edge
  - beta

stages:
  - stage: Deploy
    jobs:
      - job: publish_docker
        pool:
          vmImage: ubuntu-18.04
        variables:
          builtDockerTag: $[ stageDependencies.TestAndPackage.docker_build.outputs['foo.bar'] ]
        steps:
          - bash: echo $(builtDockerTag)
            displayName: Deploy the Docker images
