stages:
  - stage: TestAndPackage
    jobs:
      - template: templates/jobs/standard-tests-jobs.yml
      - template: templates/jobs/extended-tests-jobs.yml
      - template: templates/jobs/packaging-jobs.yml
