name: certbot
summary: Automatically configure HTTPS using Let's Encrypt
description: |
 The objective of Certbot, Let's Encrypt, and the ACME (Automated
 Certificate Management Environment) protocol is to make it possible
 to set up an HTTPS server and have it automatically obtain a
 browser-trusted certificate, without any human intervention. This is
 accomplished by running a certificate management agent on the web
 server.

 This agent is used to:
   - Automatically prove to the Let's Encrypt CA that you control the website
   - Obtain a browser-trusted certificate and set it up on your web server
   - Keep track of when your certificate is going to expire, and renew it
   - Help you revoke the certificate if that ever becomes necessary.
confinement: classic
grade: devel
base: core20
adopt-info: certbot

apps:
  certbot:
    command: bin/certbot.wrapper
    environment:
      PATH: "$SNAP/bin:$SNAP/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
      AUGEAS_LENS_LIB: "$SNAP/usr/share/augeas/lenses/dist"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH"
  renew:
    command: bin/certbot -q renew
    daemon: oneshot
    environment:
      PATH: "$SNAP/bin:$SNAP/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
      AUGEAS_LENS_LIB: $SNAP/usr/share/augeas/lenses/dist
      LD_LIBRARY_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH"
    # Run approximately twice a day with randomization
    timer: 00:00~24:00/2


parts:
  python-augeas:
    plugin: python
    source: git://github.com/basak/python-augeas
    source-branch: snap
    build-packages: [libaugeas-dev]
    python-packages:
      - wheel
    stage:
      - -pyvenv.cfg
      - -**/__pycache__
      - -bin
      - -**/RECORD
      - -**/wheel
      - -lib64
  certbot:
    plugin: python
    source: .
    constraints: [$SNAPCRAFT_PART_SRC/snap-constraints.txt]
    python-packages:
      - wheel
      - acme
      - certbot
      - certbot-apache
      - certbot-nginx
    stage:
      - -usr/lib/python3.8/sitecustomize.py # maybe unnecessary
      # Prefer cffi
      - -lib/python3.8/site-packages/augeas.py # maybe unnecessary
    stage-packages:
      - libaugeas0
      - python3-venv
    # To build cryptography and cffi if needed
    build-packages: [libffi-dev, libssl-dev]
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `cd $SNAPCRAFT_PART_SRC/certbot && git describe|sed s/^v//`
    after: [python-augeas]

  wrappers:
    plugin: dump
    source: .
    stage: [certbot.wrapper]

plugs:
  plugin:
    interface: content
    content: certbot-1
    target: $SNAP/certbot-plugin
