# Advanced pipeline for running our full test suite on demand.
trigger:
  # When changing these triggers, please ensure the documentation under
  # "Running tests in CI" is still correct.
  - azure-test-*
  - test-*
pr: none

# Any addition here should be reflected in the advanced and release pipelines.
# It is advised to declare all jobs here as templates to improve maintainability.
stages:
  - stage: Test
    jobs:
      - template: templates/jobs/standard-tests-jobs.yml
  - stage: Advanced test
    jobs:
      - template: templates/jobs/extended-tests-jobs.yml
    dependsOn: []
  - stage: Package
    jobs:
      - template: templates/jobs/packaging-jobs.yml
    dependsOn: []
