# Advanced pipeline for running our full test suite on protected branches.
trigger:
  - '*.x'
pr: none
# This pipeline is also nightly run on master
schedules:
  - cron: "0 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

stages:
  - template: templates/stages/test-and-package-stage.yml
  - template: templates/stages/deploy-stage.yml
  - template: templates/stages/notify-failure-stage.yml
