# Advanced pipeline for running our full test suite on protected branches.
trigger:
  - '*.x'
pr: none
# This pipeline is also nightly run on master
schedules:
  - cron: "0 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

stages:
  - stage: Build_Test_Package
    jobs:
      # Any addition here should be reflected in the advanced-test and release pipelines.
      # It is advised to declare all jobs here as templates to improve maintainability.
#      - template: templates/standard-tests-jobs.yml
#      - template: templates/extended-tests-jobs.yml
      - template: templates/packaging-jobs.yml
  - stage: Deploy
    jobs:
      - template: templates/deploy-jobs.yml
  - template: templates/notify-failure-steps.yml
