# Advanced pipeline for running our full test suite on protected branches.
trigger:
  - '*.x'
pr: none
# This pipeline is also nightly run on master
schedules:
  - cron: "0 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

stages:
  - stage: Test&Package
    jobs:
      # Any addition here should be reflected in the advanced-test and release pipelines.
      # It is advised to declare all jobs here as templates to improve maintainability.
      - template: templates/jobs/standard-tests-jobs.yml
      - template: templates/jobs/extended-tests-jobs.yml
      - template: templates/jobs/packaging-jobs.yml
#  - stage: Deploy
#    jobs:
#      - template: templates/jobs/deployment-jobs.yml
  - template: templates/stages/notify-failure-stage.yml
