# Release pipeline to build and deploy Certbot for Windows for GitHub release tags
trigger:
  tags:
    include:
      - v*
pr: none

jobs:
  # Any addition here should be reflected in the advanced and advanced-test pipelines.
  # It is advised to declare all jobs here as templates to improve maintainability.
  - template: templates/standard-tests.yml
  - template: templates/packaging.yml
  - template: templates/changelog.yml
