# Release pipeline to build and deploy Certbot for Windows for GitHub release tags
trigger:
  tags:
    include:
      - v*
pr: none

# Any addition here should be reflected in the advanced and advanced-test pipelines.
# It is advised to declare all jobs here as templates to improve maintainability.
stage:
  - stage: Build_Test_Package
    jobs:
      - template: templates/jobs/standard-tests-jobs.yml
      - template: templates/jobs/extended-tests-jobs.yml
      - template: templates/jobs/packaging-jobs.yml
      - template: templates/jobs/changelog-jobs.yml
  - stage: Deploy
    jobs:
      - template: templates/jobs/deployment-jobs.yml
  - template: templates/stages/notify-failure-stage.yml
